### ISSUE TITLE
changes on /reputation/space/settings don't save

### ISSUE THREAD

**Issue by globeFrEak** [globeFrEak/humhub-modules-reputation#6]

**Comment by joseph-kuruvilla** [comment]
in models reputationBase.php file add some code in getSpaceSettings function
$module = Yii::$app->getModule('reputation');
   $contentContainerId=$module->settings->space()->contentContainer->contentContainerRecord->id;       
        $getSettings = ContentContainerSetting::findAll(['module_id' => 'reputation', 'contentcontainer_id' => $contentContainerId]);


rest of the code are same .reason it won't work is $container->id is the space id itself. not contentcontainerid.
